### ISSUE TITLE
Background images for cards seems not to work.

### ISSUE THREAD

**Issue by BorjaRuizReverter** [horberlan/CyberFuture#6]
Background images for cards seems not to work. 

As it follows on the readme, the "background" should be a variable inside Cards so that something as this:

background="#333333"

or this:

background="https://www.whatever/whatever_public_image.png"

should work.  However, none of these change anything at the background of the Card component.

**Comment by horberlan** [comment]
it is necessary to import the image and concatenate it in the `background` prop:
![image](https://user-images.githubusercontent.com/46747395/224582672-56adf3fd-67b3-4900-a9c7-afdd8709a333.png)

![image](https://user-images.githubusercontent.com/46747395/224582581-afafca53-b2e8-42d9-a0ae-07010b602fea.png)
I will add the necessary typing so as not to present an error in the compiler.
